const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.resolve(__dirname, '..');
const html = fs.readFileSync(path.join(root, 'public/index.html'), 'utf8');
for (const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g)) new vm.Script(match[1]);
new vm.Script(fs.readFileSync(path.join(root, 'public/workbench.js'), 'utf8'));
for (const name of ['workbench.js', 'workbench.css']) if (!fs.existsSync(path.join(root, 'public', name))) throw new Error(`Missing asset: ${name}`);
fs.mkdirSync(path.join(root, 'dist'), { recursive: true });
fs.cpSync(path.join(root, 'public'), path.join(root, 'dist'), { recursive: true });
console.log('Static app validated and built.');
